### ISSUE TITLE
Website's source

### ISSUE THREAD

**Issue by IonicaBizau** [github/octicons#30]
Is https://octicons.github.com/ website open source? If so, where can we find the soruce code?

**Comment by IonicaBizau** [comment]
@cameronmcefee I just found a small issue:

![image](https://cloud.githubusercontent.com/assets/2864371/5694680/8cd64434-997c-11e4-9789-06c565b2382d.png)

:smile:

**Comment by cameronmcefee** [comment]
Thanks for the bump on the thread @IonicaBizau. I had a little time this morning so I've added the autofocus you suggested on the index page, and have unconstrained the wider logos in the search list.

**Comment by IonicaBizau** [comment]
Nice! Thank you!

**Comment by IonicaBizau** [comment]
@cameronmcefee Also, it would be nice if we could navigate with the <kbd>↑</kbd> and <kbd>↓</kbd> keys through the dropdown options that appear on search:

 1. Search for something
   ![image](https://cloud.githubusercontent.com/assets/2864371/5735276/2fd4b6ce-9bcc-11e4-9bc3-d4fc51a7a942.png)

 2. <kbd>↓</kbd>
   ![image](https://cloud.githubusercontent.com/assets/2864371/5735295/74f30fa8-9bcc-11e4-873e-d87ab0ce5938.png)

Actually this is already possible with <kbd>Tab</kbd>, but it would be even better with up-down keys.

I wrote this little script that adds this feature, in my browser :smile: 

```js
(function ($) {
    var ACTIVE = "navigation-focus";
    $(window).on("keydown", function (e) {
      
      console.log(e.which)
      if (!/^40|38|13$/.test(e.which.toString())) { return; }
      
      var $dropdown = $(".search-results.js-results.is-showing");
      console.log($dropdown)
      if (!$dropdown.length) { return; }
      var $selected = $("." + ACTIVE, $dropdown);
      S = $selected
      if (!$selected.length) {
        $selected = $(".js-search-result:not(.is-hidden)", $dropdown)[e.which === 40 ? "first" : "last"]();
        $selected.addClass(ACTIVE);
      }

      switch (e.which) {
        case 40:
          console.log("DOWN");
          var $next = $selected.nextAll(":not(.is-hidden):first");
          $selected.removeClass(ACTIVE);
          $next.length
            ? $next.addClass(ACTIVE)
            : $(".js-search-result:first:not(.is-hidden)", $dropdown).addClass(ACTIVE)
            ;
          break;
        case 38:
          console.log("Up");
          var $prev = $selected.prevAll(":not(.is-hidden):first");
          $selected.removeClass(ACTIVE);
          $prev.length
          ? $prev.addClass(ACTIVE)
          : $(".js-search-result:last", $dropdown).addClass(ACTIVE)
          ;
          break;
        case 13:
          window.location = $selected.attr("href");
          break;
      }
    })
})($);
```

And another fix needed is to add:

```css
a.logo:hover {
    text-decoration: none;
}
```

(a small underline appears on Firefox, when hovering the logo icons)

**Comment by IonicaBizau** [comment]
I added [it in my Tampermonkey scripts](https://github.com/IonicaBizau/dotfiles/commit/87f590f155701e2e0084041bbf9a31b0c125ceda). :smile: 

The issue with the underline, appears on Chrome too.
