### ISSUE TITLE
Redesign light-bulb icon

### ISSUE THREAD

**Issue by IonicaBizau** [github/octicons#31]
When the [`octicon-ligtht-bulb` icon](https://octicons.github.com/icon/light-bulb/) (:bulb:) is small, it looks like a skull (:skull:), more or less. :smile: 

> ![image](https://cloud.githubusercontent.com/assets/2864371/5432243/fa565234-8440-11e4-8813-7150d742a9cd.png)

**Comment by aaronshekey** [comment]
Fixed in 3.0.0

**Comment by IonicaBizau** [comment]
@aaronshekey Thank you! :cake: Looks awesome!

/cc @adioo :smile:
