### ISSUE TITLE
Building scripts

### ISSUE THREAD

**Issue by eksperimental** [github/octicons#36]
Hi, thanks for sharing these fonts,
I' m just wondering we are using only 2 of the icons, and it's adding too much load for the page for only two icons...
do you mind sharing the scripts you used for building the whole package. that way if it's based from on the svg files (as i guess), i can edit that file and rebuild it according to our own needs,

if that's not and option, a little bit of guidance on how I may achieve this will be appreciated
thanks

**Comment by cameronmcefee** [comment]
Hi @eksperimental, sorry for the slow response. We rolled our own generator, so providing the build scripts isn't an option. If you're curious about it how it works, you can learn more here: https://github.com/github/octicons/issues/24

As for rebuilding it, you could probably run the .ttf through http://www.fontsquirrel.com/tools/webfont-generator and specify only the subset of unicodes you want to include. Alternative you could make the crazy choice and decompile/recompile with http://sourceforge.net/projects/fonttools/ or roll your own solution with awesome libraries provided by https://github.com/fontello/

**Comment by eksperimental** [comment]
thanks a lot @cameronmcefee , I solved my own issue using this really nice service called: https://icomoon.io/
which basically allows you to select the characters/icons you want from any font, and repackage it.
So we are using octicon for elixir-lang.org but we only included the two icons we needed
I will definitely have a look at those links for future use
cheers

**Comment by cameronmcefee** [comment]
Ah yeah, I forgot about Icomoon. There are a few out there like this. For octicons it's totally cool, but be sure to consult the licenses for fonts you pick a part this way. Some don't permit that sort of decompiling/redistribution.
