### ISSUE TITLE
mark-github.svg icon corrupted

### ISSUE THREAD

**Issue by jackmu95** [github/octicons#40]
After [this](https://github.com/github/octicons/commit/59c60de7f1af753b5e364386c6dc144d3394d8d9) commit the **mark-github.svg** icon is corrupted at the top of the circle.
The difference can be seen [here](https://github.com/github/octicons/commit/59c60de7f1af753b5e364386c6dc144d3394d8d9?short_path=8e50b48#diff-8e50b48f44e683a99abc6fe8477ddb45).

Please fix this :)

**Comment by jackmu95** [comment]
@jeejkang Thanks!

**Comment by jeejkang** [comment]
:metal: Thanks for bringing this up @jackmu95

**Comment by jackmu95** [comment]
No problem :) I needed the icon for a upcoming project I'am working on and noticed it during the editing process in Illustrator.
