### ISSUE TITLE
NPM package

### ISSUE THREAD

**Issue by max** [github/octicons#41]
I noticed that Octicons are not on NPM but the repo includes a `package.json`. I went ahead and published it and am more than happy to transfer it to a maintainer of the repo.

**Comment by cameronmcefee** [comment]
Hi @max,

Thanks, I should have done that a while ago. You can transfer it to me.

**Comment by max** [comment]
Done. https://www.npmjs.com/package/octicons

**Comment by cameronmcefee** [comment]
Much appreciated! Thanks @max

**Comment by SamyPesse** [comment]
Any reasons why latest releases are not on NPM (`3.3.0` and `3.2.0`) ?
