### ISSUE TITLE
Verification of npmjs repo

### ISSUE THREAD

**Issue by Martii** [github/octicons#45]
Hello... I was hoping to get some verification if https://www.npmjs.com/package/octicons is the official npmjs registry distribution of this project.

If so, it would also be appreciated to have this mentioned in the [README.md](https://github.com/github/octicons/blob/master/README.md). TIA

**Comment by cameronmcefee** [comment]
Hi @Martii,

That package was published by a user on our behalf without permission, but transferred it to me. Due to the confusion showing a non-GitHub publisher I've reached out to NPM to see if that can be changed. If it's possible to change it then, yes, that'll be the official distribution. If not, I may republish. I'll report back here once they get back to me.

**Comment by Martii** [comment]
Thanks. I didn't recognize the username from any contributor here which raised an eyebrow. If it helps any for intel I ran into this situation last year on another project at t0m/select2-bootstrap-css#51

**Comment by Majiir** [comment]
Hi @cameronmcefee,

Do you have any update on this? I tried switching my Bower dependencies over to NPM today, and found that the NPM version for Octicons isn't up-to-date. I'd love to be able to eliminate Bower from my toolchain. Thanks!

**Comment by cameronmcefee** [comment]
Sorry, never published a npm package before. It looks like the issues around identity weren't any sort of ownership thing but rather just that I didn't personally publish it. I assumed the versioning was automatic based on the tags the way bower does it, but apparently I have to manually publish.

That is to say, I've published 2.4.1, which now has my name associated with it, so I think everything is cool.

**Comment by Majiir** [comment]
Looks good, thanks!

**Comment by Martii** [comment]
@cameronmcefee 
Last I tested on npmjs.com they keep all versions... so it won't allow you to replace one. e.g. strict semver increment with `$ npm publish`... although you can decrement to something that doesn't exist. Thanks for doing that... will be nice to have it all in one chunk there as git urls take longer to download.
