### ISSUE TITLE
Encoding::UndefinedConversionError: "\x81" to UTF-8 in conversion from Windows-1252 to UTF-8

### ISSUE THREAD

**Issue by ericrange** [github/octicons#55]
Encoding::UndefinedConversionError: "\x81" to UTF-8 in conversion from Windows-1252 to UTF-8

this message appears if you want to include octicon.css in my assets.

**Comment by shiftkey** [comment]
@ericrange which tool is raising this?

**Comment by ericrange** [comment]
grunt-contrib-sass (latest version)

**Comment by ericrange** [comment]
i have to remove all comments everytime... then it works

**Comment by ericrange** [comment]
maybe you could add octicon.min.css to the bower repo. without comments?

**Comment by cameronmcefee** [comment]
Thanks for the report @ericrange!

> grunt-contrib-sass (latest version)
> i have to remove all comments in the octicon.css (bower) everytime... then it works

Unless I misunderstand what you're saying, your gruntfile should only be running .sass/.scss files through grunt-contrib-sass, so technically this shouldn't be an issue.
