### ISSUE TITLE
Any hope to add more icons? 

### ISSUE THREAD

**Issue by mkrdip** [github/octicons#61]
I know, only icons used by Github projects are added here. But how about creating a fully packaged icon set for web designers? So they can implement it on their themes/templates?

Few more icons (Social: Facebook, Twiiter, LinkedIn, Skype etc)

e.g: http://genericons.com
http://pfefferle.github.io/openwebicons

**Comment by cameronmcefee** [comment]
Hi @mkrdip,

Thanks for the request! At this time, Octicons will remain only GitHub icons, specifically those needed for GitHub.com. However, the license permits you to use the source of the files to compile your own icon fonts, so you can take icons from Octicons and merge them with icons of other sets to meet your specific needs.
