### ISSUE TITLE
How to use octicons with angular-material

### ISSUE THREAD

**Issue by VikramTiwari** [github/octicons#62]
I can use material icons by including the font-file and using ```<md-icon class="material-icons">face</md-icon>``` and it serves the material icons. Same for font-awesome.

Tried doing the same for octicons to no avail. Anything i am missing?

PS: This works fine though. ```<span class="octicon octicon-mark-github"></span>``` . But would like to use ```md-icon``` method

**Comment by cameronmcefee** [comment]
From a look at the https://github.com/angular/material source, it looks like you might need to set [some sort of configuration option](https://github.com/angular/material/blob/a9bc5345adeef87145f25624da7e4cd6ee4f3364/src/components/icon/iconDirective.js#L161-L163) to make it work.

**Comment by VikramTiwari** [comment]
Hi @cameronmcefee - I seem to have trouble using just octicons. I am using fa using the same method.

Please find source code here: https://github.com/VikramTiwari/vikramtiwari.github.com/blob/master/index.html#L42
and 
https://github.com/VikramTiwari/vikramtiwari.github.com/blob/master/app.js#L17
