### ISSUE TITLE
HTML source for Octicons site?

### ISSUE THREAD

**Issue by jm3** [github/octicons#66]
I'd like to create a handy copy-paste cheat sheet like the Octicons site with its helpful paste codes.

Is the generator for the Octicons website available? I'm assuming it's a Jekyll / GitHub pages joint?

**Comment by IonicaBizau** [comment]
I asked the same in #30. The source is not open.

@cameronmcefee  Any updates on [this](https://github.com/github/octicons/issues/30#issuecomment-66799715)?

**Comment by cameronmcefee** [comment]
Unfortunately, I've had bigger fish to fry lately, so I haven't been able to get opening the site up. Also unfortunately, this may be the case for a while.

To your actual goal, @jm3 you should be able to to pretty easily write a jquery/js script that would extract the information. For example, dropping this into the console will get you an array of all the classname/character pairs:

```
$('.js-icon-item').map(function(i, el){
  return {
    class: $(el).attr('data-name'),
    char: $(el).find('[data-clipboard-text]').attr('data-clipboard-text')
  } 
}).toArray()
```

**Comment by jm3** [comment]
@cameronmcefee thanks, great answer!
