### ISSUE TITLE
Distribute via Homebrew

### ISSUE THREAD

**Issue by benbalter** [github/octicons#70]
It'd be awesome if Octicons were part of https://github.com/caskroom/homebrew-fonts. I'd love to be able to install Octicons via `brew cask install font-octicons` in a way that can easily be kept up to date without manually downloading each time.

**Comment by cameronmcefee** [comment]
What's the process for maintaining this? We're already [running into issues](https://github.com/github/octicons/issues/67) with working in having to manually publish to npm along with the rest of the publishing flow. Is this going to add another list of things that may get ignored, or is it something that can be/is automated?

**Comment by benbalter** [comment]
Spiked out https://github.com/caskroom/homebrew-fonts/pull/396, which I believe should be all that's involved. The tradeoff with the way release-downloads work, it has to pull from master (or we'd have to submit a pull request with each release), but this way is set-it-and-forget-it.

**Comment by cameronmcefee** [comment]
I think that's fine. Master is generally always the latest release, with the exception of the delay between merging a pr and tagging a new release.

**Comment by benbalter** [comment]
...and we're live.

You can now install the latest version of octicons via:

```
brew tap "caskroom/fonts"
brew cask install "font-octicons"
```

or, if you are using a `.Brewfile` ([like so](https://github.com/benbalter/dotfiles/commit/38ae0e6cf6597e399679156c3bacd8054a8d9cb7)):

```
tap "caskroom/fonts"
cask "font-octicons"
```

**Comment by cameronmcefee** [comment]
@benbalter mind updating the readme to represent this?
