### ISSUE TITLE
Error installing via homebrew

### ISSUE THREAD

**Issue by dougaitken** [github/octicons#72]
I tried to follow the instructions to install via Homebrew, however ran into an error. Am I doing something incorrect or has something changed since #71 & #70 ?

![doug_ _bash_ _132x30](https://cloud.githubusercontent.com/assets/52214/10623424/c9c26416-7786-11e5-991e-0157f2e582bc.jpg)

**Comment by cameronmcefee** [comment]
cc @benbalter

**Comment by benbalter** [comment]
@dougaitken see https://github.com/github/octicons/pull/73. You'll need to run `brew install caskroom/cask/brew-cask` first to install `brew-cask`.

**Comment by dougaitken** [comment]
Nice one @benbalter, cheers!
